// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_BUN2TQBN1C3tzLLZWXybLQcpMg-pKWc',
    appId: '1:102745669648:web:56411c4c96248032254a95',
    messagingSenderId: '102745669648',
    projectId: 'viberant-pos',
    authDomain: 'viberant-pos.firebaseapp.com',
    storageBucket: 'viberant-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbsjNDn9RusYuBqsQEknkqBFiyP--ZVA',
    appId: '1:102745669648:android:d6ff41a0f5692ccb254a95',
    messagingSenderId: '102745669648',
    projectId: 'viberant-pos',
    storageBucket: 'viberant-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNge_IR0tS5g-knQwVMYKRrdRN3S6Gscg',
    appId: '1:102745669648:ios:85106c3f5b0f33f5254a95',
    messagingSenderId: '102745669648',
    projectId: 'viberant-pos',
    storageBucket: 'viberant-pos.firebasestorage.app',
    iosBundleId: 'com.example.viberantPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNge_IR0tS5g-knQwVMYKRrdRN3S6Gscg',
    appId: '1:102745669648:ios:85106c3f5b0f33f5254a95',
    messagingSenderId: '102745669648',
    projectId: 'viberant-pos',
    storageBucket: 'viberant-pos.firebasestorage.app',
    iosBundleId: 'com.example.viberantPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_BUN2TQBN1C3tzLLZWXybLQcpMg-pKWc',
    appId: '1:102745669648:web:3ff62c13d50395cc254a95',
    messagingSenderId: '102745669648',
    projectId: 'viberant-pos',
    authDomain: 'viberant-pos.firebaseapp.com',
    storageBucket: 'viberant-pos.firebasestorage.app',
  );
}
